version: "3.8"
services:
  app:
    build:
      context: .
      target: development
      dockerfile: ../../Dockerfiles/Flask_auth/Dockerfile
    image: ecom_authorization
    command: ["python", "-m","app"]
    environment:
      - PORT_APP=4000
      - SQLALCHEMY_USERNAME:pguser
      - SQLALCHEMY_PASSWORD:pgpassword
      - SQLALCHEMY_DATABASE_NAME:auth_db
      - JWT_SECRET_KEY=super-secret-key
      - TRACING_ENABLED=true
      - TRACING_AGENT_HOST_NAME=jaeger
    ports:
      - "127.0.0.1:4000:4000"
    env_file:
      - ./.env
    volumes:
      - ./src/app:/home/app/src/app
      - ./src/migrations:/home/app/src/migrations
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  postgres:
    image: postgres:14
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: auth_db



volumes:
  redis-data:
    driver: "local"
  postgres-data:
    driver: "local"
